name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Add manual trigger support

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov keyring tiktoken
        # Install the package in development mode
        pip install -e .
        
    - name: Verify imports
      run: |
        # Create and run a simple import test to verify the environment
        cat > import_test.py << 'EOL'
        import sys
        sys.path.insert(0, '.')
        
        # Create a mock keyring module to avoid backend issues
        import types
        mock_keyring = types.ModuleType('keyring')
        
        # Add mock functions
        def get_password(service_name, username):
            return "mock-password"
            
        def set_password(service_name, username, password):
            pass
            
        def delete_password(service_name, username):
            return True
            
        mock_keyring.get_password = get_password
        mock_keyring.set_password = set_password
        mock_keyring.delete_password = delete_password
        
        # Replace the real keyring with our mock
        sys.modules['keyring'] = mock_keyring
        print("✅ Created mock keyring module")
        
        # Check required dependencies
        required_modules = ['tiktoken']
        missing = []
        
        for module in required_modules:
            try:
                __import__(module)
                print(f"✅ {module} module is available")
            except ImportError as e:
                missing.append(module)
                print(f"❌ ERROR: {e}")
        
        if missing:
            print(f"Missing modules: {', '.join(missing)}")
            sys.exit(1)
        
        # Now try the project imports
        try:
            from src.generators import implementation_prompt_generator_simple
            print("✅ Import test successful!")
        except ImportError as e:
            print(f"❌ Import failed: {e}")
            # Try to determine which dependency is missing
            import traceback
            traceback.print_exc()
            # Print the Python path to help debug
            print("\nPython path:")
            for p in sys.path:
                print(f"  {p}")
            sys.exit(1)
        EOL
        python import_test.py
        
    - name: Run tests
      run: |
        # Set PYTHONPATH to include the project root
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        # Create mock keyring patch
        cat > patch_keyring.py << 'EOL'
        import sys
        import types
        
        # Mock keyring implementation
        class MockKeyringBackend:
            """Simple in-memory keyring backend for testing."""
            
            def __init__(self):
                self.passwords = {}
            
            def set_password(self, service_name, username, password):
                """Store a password."""
                key = f"{service_name}:{username}"
                self.passwords[key] = password
                
            def get_password(self, service_name, username):
                """Retrieve a password."""
                key = f"{service_name}:{username}"
                return self.passwords.get(key)
                
            def delete_password(self, service_name, username):
                """Delete a password."""
                key = f"{service_name}:{username}"
                if key in self.passwords:
                    del self.passwords[key]
                    return True
                return False

        # Create a global instance
        backend = MockKeyringBackend()

        # Create a mock keyring module
        mock_keyring = types.ModuleType('keyring')
        mock_keyring.get_password = backend.get_password
        mock_keyring.set_password = backend.set_password
        mock_keyring.delete_password = backend.delete_password
        
        # Replace the real keyring with our mock
        sys.modules['keyring'] = mock_keyring
        print("✅ Keyring module patched for CI environment")
        EOL
        
        # Run pytest with our keyring patch
        python -c "exec(open('patch_keyring.py').read()); import pytest; pytest.main(['-xvs', '-c', 'github-pytest.ini', 'tests/test_config.py', 'tests/test_utils/test_config.py', '--import-mode=importlib'])"
        
    - name: Run coverage
      run: |
        # Set PYTHONPATH to include the project root
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        # Use the same keyring patch for coverage
        python -c "exec(open('patch_keyring.py').read()); import pytest; pytest.main(['--cov=src', '-xvs', '-c', 'github-pytest.ini', '--import-mode=importlib', 'tests/test_config.py', 'tests/test_utils/test_config.py', '--cov-report=xml'])"
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
