name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Add manual trigger support

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov keyring tiktoken
        # Install the package in development mode
        pip install -e .
        
    - name: Verify imports
      run: |
        # Create and run a simple import test to verify the environment
        cat > import_test.py << 'EOL'
        import sys
        sys.path.insert(0, '.')
        
        # Check required dependencies
        required_modules = ['keyring', 'tiktoken']
        missing = []
        
        for module in required_modules:
            try:
                __import__(module)
                print(f"✅ {module} module is available")
            except ImportError as e:
                missing.append(module)
                print(f"❌ ERROR: {e}")
        
        if missing:
            print(f"Missing modules: {', '.join(missing)}")
            sys.exit(1)
        
        # Now try the project imports
        try:
            from src.generators import implementation_prompt_generator_simple
            print("✅ Import test successful!")
        except ImportError as e:
            print(f"❌ Import failed: {e}")
            # Try to determine which dependency is missing
            import traceback
            traceback.print_exc()
            # Print the Python path to help debug
            print("\nPython path:")
            for p in sys.path:
                print(f"  {p}")
            sys.exit(1)
        EOL
        python import_test.py
        
    - name: Run tests
      run: |
        # Set PYTHONPATH to include the project root
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        # Run pytest with verbose output and specific config for GitHub
        python -m pytest tests/unit/ -v -c github-pytest.ini --import-mode=importlib
        
    - name: Run coverage
      run: |
        # Set PYTHONPATH to include the project root
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pytest --cov=src tests/unit/ --cov-report=xml -c github-pytest.ini --import-mode=importlib
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
